name: "Build"
on:
  pull_request:
  push:
   branches:
     - master
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: cachix/install-nix-action@v16
    - uses: cachix/cachix-action@v10
      with:
        name: anmonteiro
        signingKey: '${{ secrets.CACHIX_SIGNING_KEY }}'
    - name: "Run nix-build"
      run: nix-build ./nix/ci.nix
